# Generated by Django 3.1.7 on 2021-03-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imge_url',
            new_name='image_url',
        ),
    ]
